
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EmployeeRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EmployeeRequest
 * 
 */
export type EmployeeRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$EmployeeRequestPayload>

export type AggregateEmployeeRequest = {
  _count: EmployeeRequestCountAggregateOutputType | null
  _min: EmployeeRequestMinAggregateOutputType | null
  _max: EmployeeRequestMaxAggregateOutputType | null
}

export type EmployeeRequestMinAggregateOutputType = {
  id: string | null
  userId: string | null
  type: string | null
  description: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EmployeeRequestMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  type: string | null
  description: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EmployeeRequestCountAggregateOutputType = {
  id: number
  userId: number
  type: number
  description: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EmployeeRequestMinAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  description?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type EmployeeRequestMaxAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  description?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type EmployeeRequestCountAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  description?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EmployeeRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmployeeRequest to aggregate.
   */
  where?: Prisma.EmployeeRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmployeeRequests to fetch.
   */
  orderBy?: Prisma.EmployeeRequestOrderByWithRelationInput | Prisma.EmployeeRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmployeeRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmployeeRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmployeeRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EmployeeRequests
  **/
  _count?: true | EmployeeRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmployeeRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmployeeRequestMaxAggregateInputType
}

export type GetEmployeeRequestAggregateType<T extends EmployeeRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateEmployeeRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmployeeRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateEmployeeRequest[P]>
}




export type EmployeeRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmployeeRequestWhereInput
  orderBy?: Prisma.EmployeeRequestOrderByWithAggregationInput | Prisma.EmployeeRequestOrderByWithAggregationInput[]
  by: Prisma.EmployeeRequestScalarFieldEnum[] | Prisma.EmployeeRequestScalarFieldEnum
  having?: Prisma.EmployeeRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmployeeRequestCountAggregateInputType | true
  _min?: EmployeeRequestMinAggregateInputType
  _max?: EmployeeRequestMaxAggregateInputType
}

export type EmployeeRequestGroupByOutputType = {
  id: string
  userId: string
  type: string
  description: string
  status: string
  createdAt: Date
  updatedAt: Date
  _count: EmployeeRequestCountAggregateOutputType | null
  _min: EmployeeRequestMinAggregateOutputType | null
  _max: EmployeeRequestMaxAggregateOutputType | null
}

type GetEmployeeRequestGroupByPayload<T extends EmployeeRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmployeeRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmployeeRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmployeeRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmployeeRequestGroupByOutputType[P]>
      }
    >
  >



export type EmployeeRequestWhereInput = {
  AND?: Prisma.EmployeeRequestWhereInput | Prisma.EmployeeRequestWhereInput[]
  OR?: Prisma.EmployeeRequestWhereInput[]
  NOT?: Prisma.EmployeeRequestWhereInput | Prisma.EmployeeRequestWhereInput[]
  id?: Prisma.StringFilter<"EmployeeRequest"> | string
  userId?: Prisma.StringFilter<"EmployeeRequest"> | string
  type?: Prisma.StringFilter<"EmployeeRequest"> | string
  description?: Prisma.StringFilter<"EmployeeRequest"> | string
  status?: Prisma.StringFilter<"EmployeeRequest"> | string
  createdAt?: Prisma.DateTimeFilter<"EmployeeRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EmployeeRequest"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type EmployeeRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type EmployeeRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EmployeeRequestWhereInput | Prisma.EmployeeRequestWhereInput[]
  OR?: Prisma.EmployeeRequestWhereInput[]
  NOT?: Prisma.EmployeeRequestWhereInput | Prisma.EmployeeRequestWhereInput[]
  userId?: Prisma.StringFilter<"EmployeeRequest"> | string
  type?: Prisma.StringFilter<"EmployeeRequest"> | string
  description?: Prisma.StringFilter<"EmployeeRequest"> | string
  status?: Prisma.StringFilter<"EmployeeRequest"> | string
  createdAt?: Prisma.DateTimeFilter<"EmployeeRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EmployeeRequest"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type EmployeeRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EmployeeRequestCountOrderByAggregateInput
  _max?: Prisma.EmployeeRequestMaxOrderByAggregateInput
  _min?: Prisma.EmployeeRequestMinOrderByAggregateInput
}

export type EmployeeRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmployeeRequestScalarWhereWithAggregatesInput | Prisma.EmployeeRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmployeeRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmployeeRequestScalarWhereWithAggregatesInput | Prisma.EmployeeRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EmployeeRequest"> | string
  userId?: Prisma.StringWithAggregatesFilter<"EmployeeRequest"> | string
  type?: Prisma.StringWithAggregatesFilter<"EmployeeRequest"> | string
  description?: Prisma.StringWithAggregatesFilter<"EmployeeRequest"> | string
  status?: Prisma.StringWithAggregatesFilter<"EmployeeRequest"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EmployeeRequest"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EmployeeRequest"> | Date | string
}

export type EmployeeRequestCreateInput = {
  id?: string
  type: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRequestsInput
}

export type EmployeeRequestUncheckedCreateInput = {
  id?: string
  userId: string
  type: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EmployeeRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRequestsNestedInput
}

export type EmployeeRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployeeRequestCreateManyInput = {
  id?: string
  userId: string
  type: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EmployeeRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployeeRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployeeRequestListRelationFilter = {
  every?: Prisma.EmployeeRequestWhereInput
  some?: Prisma.EmployeeRequestWhereInput
  none?: Prisma.EmployeeRequestWhereInput
}

export type EmployeeRequestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmployeeRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EmployeeRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EmployeeRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EmployeeRequestCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EmployeeRequestCreateWithoutUserInput, Prisma.EmployeeRequestUncheckedCreateWithoutUserInput> | Prisma.EmployeeRequestCreateWithoutUserInput[] | Prisma.EmployeeRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmployeeRequestCreateOrConnectWithoutUserInput | Prisma.EmployeeRequestCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EmployeeRequestCreateManyUserInputEnvelope
  connect?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
}

export type EmployeeRequestUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EmployeeRequestCreateWithoutUserInput, Prisma.EmployeeRequestUncheckedCreateWithoutUserInput> | Prisma.EmployeeRequestCreateWithoutUserInput[] | Prisma.EmployeeRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmployeeRequestCreateOrConnectWithoutUserInput | Prisma.EmployeeRequestCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EmployeeRequestCreateManyUserInputEnvelope
  connect?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
}

export type EmployeeRequestUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EmployeeRequestCreateWithoutUserInput, Prisma.EmployeeRequestUncheckedCreateWithoutUserInput> | Prisma.EmployeeRequestCreateWithoutUserInput[] | Prisma.EmployeeRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmployeeRequestCreateOrConnectWithoutUserInput | Prisma.EmployeeRequestCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EmployeeRequestUpsertWithWhereUniqueWithoutUserInput | Prisma.EmployeeRequestUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EmployeeRequestCreateManyUserInputEnvelope
  set?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
  disconnect?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
  delete?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
  connect?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
  update?: Prisma.EmployeeRequestUpdateWithWhereUniqueWithoutUserInput | Prisma.EmployeeRequestUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EmployeeRequestUpdateManyWithWhereWithoutUserInput | Prisma.EmployeeRequestUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EmployeeRequestScalarWhereInput | Prisma.EmployeeRequestScalarWhereInput[]
}

export type EmployeeRequestUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EmployeeRequestCreateWithoutUserInput, Prisma.EmployeeRequestUncheckedCreateWithoutUserInput> | Prisma.EmployeeRequestCreateWithoutUserInput[] | Prisma.EmployeeRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmployeeRequestCreateOrConnectWithoutUserInput | Prisma.EmployeeRequestCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EmployeeRequestUpsertWithWhereUniqueWithoutUserInput | Prisma.EmployeeRequestUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EmployeeRequestCreateManyUserInputEnvelope
  set?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
  disconnect?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
  delete?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
  connect?: Prisma.EmployeeRequestWhereUniqueInput | Prisma.EmployeeRequestWhereUniqueInput[]
  update?: Prisma.EmployeeRequestUpdateWithWhereUniqueWithoutUserInput | Prisma.EmployeeRequestUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EmployeeRequestUpdateManyWithWhereWithoutUserInput | Prisma.EmployeeRequestUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EmployeeRequestScalarWhereInput | Prisma.EmployeeRequestScalarWhereInput[]
}

export type EmployeeRequestCreateWithoutUserInput = {
  id?: string
  type: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EmployeeRequestUncheckedCreateWithoutUserInput = {
  id?: string
  type: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EmployeeRequestCreateOrConnectWithoutUserInput = {
  where: Prisma.EmployeeRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.EmployeeRequestCreateWithoutUserInput, Prisma.EmployeeRequestUncheckedCreateWithoutUserInput>
}

export type EmployeeRequestCreateManyUserInputEnvelope = {
  data: Prisma.EmployeeRequestCreateManyUserInput | Prisma.EmployeeRequestCreateManyUserInput[]
}

export type EmployeeRequestUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.EmployeeRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.EmployeeRequestUpdateWithoutUserInput, Prisma.EmployeeRequestUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.EmployeeRequestCreateWithoutUserInput, Prisma.EmployeeRequestUncheckedCreateWithoutUserInput>
}

export type EmployeeRequestUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.EmployeeRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.EmployeeRequestUpdateWithoutUserInput, Prisma.EmployeeRequestUncheckedUpdateWithoutUserInput>
}

export type EmployeeRequestUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.EmployeeRequestScalarWhereInput
  data: Prisma.XOR<Prisma.EmployeeRequestUpdateManyMutationInput, Prisma.EmployeeRequestUncheckedUpdateManyWithoutUserInput>
}

export type EmployeeRequestScalarWhereInput = {
  AND?: Prisma.EmployeeRequestScalarWhereInput | Prisma.EmployeeRequestScalarWhereInput[]
  OR?: Prisma.EmployeeRequestScalarWhereInput[]
  NOT?: Prisma.EmployeeRequestScalarWhereInput | Prisma.EmployeeRequestScalarWhereInput[]
  id?: Prisma.StringFilter<"EmployeeRequest"> | string
  userId?: Prisma.StringFilter<"EmployeeRequest"> | string
  type?: Prisma.StringFilter<"EmployeeRequest"> | string
  description?: Prisma.StringFilter<"EmployeeRequest"> | string
  status?: Prisma.StringFilter<"EmployeeRequest"> | string
  createdAt?: Prisma.DateTimeFilter<"EmployeeRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EmployeeRequest"> | Date | string
}

export type EmployeeRequestCreateManyUserInput = {
  id?: string
  type: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EmployeeRequestUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployeeRequestUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployeeRequestUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EmployeeRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  description?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employeeRequest"]>

export type EmployeeRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  description?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employeeRequest"]>

export type EmployeeRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  description?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employeeRequest"]>

export type EmployeeRequestSelectScalar = {
  id?: boolean
  userId?: boolean
  type?: boolean
  description?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EmployeeRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "type" | "description" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["employeeRequest"]>
export type EmployeeRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type EmployeeRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type EmployeeRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $EmployeeRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EmployeeRequest"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    type: string
    description: string
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["employeeRequest"]>
  composites: {}
}

export type EmployeeRequestGetPayload<S extends boolean | null | undefined | EmployeeRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload, S>

export type EmployeeRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmployeeRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmployeeRequestCountAggregateInputType | true
  }

export interface EmployeeRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EmployeeRequest'], meta: { name: 'EmployeeRequest' } }
  /**
   * Find zero or one EmployeeRequest that matches the filter.
   * @param {EmployeeRequestFindUniqueArgs} args - Arguments to find a EmployeeRequest
   * @example
   * // Get one EmployeeRequest
   * const employeeRequest = await prisma.employeeRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmployeeRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, EmployeeRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmployeeRequestClient<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EmployeeRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmployeeRequestFindUniqueOrThrowArgs} args - Arguments to find a EmployeeRequest
   * @example
   * // Get one EmployeeRequest
   * const employeeRequest = await prisma.employeeRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmployeeRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmployeeRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmployeeRequestClient<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmployeeRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeRequestFindFirstArgs} args - Arguments to find a EmployeeRequest
   * @example
   * // Get one EmployeeRequest
   * const employeeRequest = await prisma.employeeRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmployeeRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, EmployeeRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmployeeRequestClient<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmployeeRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeRequestFindFirstOrThrowArgs} args - Arguments to find a EmployeeRequest
   * @example
   * // Get one EmployeeRequest
   * const employeeRequest = await prisma.employeeRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmployeeRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmployeeRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmployeeRequestClient<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EmployeeRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EmployeeRequests
   * const employeeRequests = await prisma.employeeRequest.findMany()
   * 
   * // Get first 10 EmployeeRequests
   * const employeeRequests = await prisma.employeeRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const employeeRequestWithIdOnly = await prisma.employeeRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmployeeRequestFindManyArgs>(args?: Prisma.SelectSubset<T, EmployeeRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EmployeeRequest.
   * @param {EmployeeRequestCreateArgs} args - Arguments to create a EmployeeRequest.
   * @example
   * // Create one EmployeeRequest
   * const EmployeeRequest = await prisma.employeeRequest.create({
   *   data: {
   *     // ... data to create a EmployeeRequest
   *   }
   * })
   * 
   */
  create<T extends EmployeeRequestCreateArgs>(args: Prisma.SelectSubset<T, EmployeeRequestCreateArgs<ExtArgs>>): Prisma.Prisma__EmployeeRequestClient<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EmployeeRequests.
   * @param {EmployeeRequestCreateManyArgs} args - Arguments to create many EmployeeRequests.
   * @example
   * // Create many EmployeeRequests
   * const employeeRequest = await prisma.employeeRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmployeeRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, EmployeeRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EmployeeRequests and returns the data saved in the database.
   * @param {EmployeeRequestCreateManyAndReturnArgs} args - Arguments to create many EmployeeRequests.
   * @example
   * // Create many EmployeeRequests
   * const employeeRequest = await prisma.employeeRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EmployeeRequests and only return the `id`
   * const employeeRequestWithIdOnly = await prisma.employeeRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmployeeRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmployeeRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EmployeeRequest.
   * @param {EmployeeRequestDeleteArgs} args - Arguments to delete one EmployeeRequest.
   * @example
   * // Delete one EmployeeRequest
   * const EmployeeRequest = await prisma.employeeRequest.delete({
   *   where: {
   *     // ... filter to delete one EmployeeRequest
   *   }
   * })
   * 
   */
  delete<T extends EmployeeRequestDeleteArgs>(args: Prisma.SelectSubset<T, EmployeeRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__EmployeeRequestClient<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EmployeeRequest.
   * @param {EmployeeRequestUpdateArgs} args - Arguments to update one EmployeeRequest.
   * @example
   * // Update one EmployeeRequest
   * const employeeRequest = await prisma.employeeRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmployeeRequestUpdateArgs>(args: Prisma.SelectSubset<T, EmployeeRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__EmployeeRequestClient<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EmployeeRequests.
   * @param {EmployeeRequestDeleteManyArgs} args - Arguments to filter EmployeeRequests to delete.
   * @example
   * // Delete a few EmployeeRequests
   * const { count } = await prisma.employeeRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmployeeRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmployeeRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmployeeRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EmployeeRequests
   * const employeeRequest = await prisma.employeeRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmployeeRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, EmployeeRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmployeeRequests and returns the data updated in the database.
   * @param {EmployeeRequestUpdateManyAndReturnArgs} args - Arguments to update many EmployeeRequests.
   * @example
   * // Update many EmployeeRequests
   * const employeeRequest = await prisma.employeeRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EmployeeRequests and only return the `id`
   * const employeeRequestWithIdOnly = await prisma.employeeRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmployeeRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmployeeRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EmployeeRequest.
   * @param {EmployeeRequestUpsertArgs} args - Arguments to update or create a EmployeeRequest.
   * @example
   * // Update or create a EmployeeRequest
   * const employeeRequest = await prisma.employeeRequest.upsert({
   *   create: {
   *     // ... data to create a EmployeeRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EmployeeRequest we want to update
   *   }
   * })
   */
  upsert<T extends EmployeeRequestUpsertArgs>(args: Prisma.SelectSubset<T, EmployeeRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__EmployeeRequestClient<runtime.Types.Result.GetResult<Prisma.$EmployeeRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EmployeeRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeRequestCountArgs} args - Arguments to filter EmployeeRequests to count.
   * @example
   * // Count the number of EmployeeRequests
   * const count = await prisma.employeeRequest.count({
   *   where: {
   *     // ... the filter for the EmployeeRequests we want to count
   *   }
   * })
  **/
  count<T extends EmployeeRequestCountArgs>(
    args?: Prisma.Subset<T, EmployeeRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmployeeRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EmployeeRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmployeeRequestAggregateArgs>(args: Prisma.Subset<T, EmployeeRequestAggregateArgs>): Prisma.PrismaPromise<GetEmployeeRequestAggregateType<T>>

  /**
   * Group by EmployeeRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmployeeRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmployeeRequestGroupByArgs['orderBy'] }
      : { orderBy?: EmployeeRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmployeeRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmployeeRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EmployeeRequest model
 */
readonly fields: EmployeeRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EmployeeRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmployeeRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EmployeeRequest model
 */
export interface EmployeeRequestFieldRefs {
  readonly id: Prisma.FieldRef<"EmployeeRequest", 'String'>
  readonly userId: Prisma.FieldRef<"EmployeeRequest", 'String'>
  readonly type: Prisma.FieldRef<"EmployeeRequest", 'String'>
  readonly description: Prisma.FieldRef<"EmployeeRequest", 'String'>
  readonly status: Prisma.FieldRef<"EmployeeRequest", 'String'>
  readonly createdAt: Prisma.FieldRef<"EmployeeRequest", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EmployeeRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EmployeeRequest findUnique
 */
export type EmployeeRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * Filter, which EmployeeRequest to fetch.
   */
  where: Prisma.EmployeeRequestWhereUniqueInput
}

/**
 * EmployeeRequest findUniqueOrThrow
 */
export type EmployeeRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * Filter, which EmployeeRequest to fetch.
   */
  where: Prisma.EmployeeRequestWhereUniqueInput
}

/**
 * EmployeeRequest findFirst
 */
export type EmployeeRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * Filter, which EmployeeRequest to fetch.
   */
  where?: Prisma.EmployeeRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmployeeRequests to fetch.
   */
  orderBy?: Prisma.EmployeeRequestOrderByWithRelationInput | Prisma.EmployeeRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmployeeRequests.
   */
  cursor?: Prisma.EmployeeRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmployeeRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmployeeRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmployeeRequests.
   */
  distinct?: Prisma.EmployeeRequestScalarFieldEnum | Prisma.EmployeeRequestScalarFieldEnum[]
}

/**
 * EmployeeRequest findFirstOrThrow
 */
export type EmployeeRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * Filter, which EmployeeRequest to fetch.
   */
  where?: Prisma.EmployeeRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmployeeRequests to fetch.
   */
  orderBy?: Prisma.EmployeeRequestOrderByWithRelationInput | Prisma.EmployeeRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmployeeRequests.
   */
  cursor?: Prisma.EmployeeRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmployeeRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmployeeRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmployeeRequests.
   */
  distinct?: Prisma.EmployeeRequestScalarFieldEnum | Prisma.EmployeeRequestScalarFieldEnum[]
}

/**
 * EmployeeRequest findMany
 */
export type EmployeeRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * Filter, which EmployeeRequests to fetch.
   */
  where?: Prisma.EmployeeRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmployeeRequests to fetch.
   */
  orderBy?: Prisma.EmployeeRequestOrderByWithRelationInput | Prisma.EmployeeRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EmployeeRequests.
   */
  cursor?: Prisma.EmployeeRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmployeeRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmployeeRequests.
   */
  skip?: number
  distinct?: Prisma.EmployeeRequestScalarFieldEnum | Prisma.EmployeeRequestScalarFieldEnum[]
}

/**
 * EmployeeRequest create
 */
export type EmployeeRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a EmployeeRequest.
   */
  data: Prisma.XOR<Prisma.EmployeeRequestCreateInput, Prisma.EmployeeRequestUncheckedCreateInput>
}

/**
 * EmployeeRequest createMany
 */
export type EmployeeRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EmployeeRequests.
   */
  data: Prisma.EmployeeRequestCreateManyInput | Prisma.EmployeeRequestCreateManyInput[]
}

/**
 * EmployeeRequest createManyAndReturn
 */
export type EmployeeRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * The data used to create many EmployeeRequests.
   */
  data: Prisma.EmployeeRequestCreateManyInput | Prisma.EmployeeRequestCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EmployeeRequest update
 */
export type EmployeeRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a EmployeeRequest.
   */
  data: Prisma.XOR<Prisma.EmployeeRequestUpdateInput, Prisma.EmployeeRequestUncheckedUpdateInput>
  /**
   * Choose, which EmployeeRequest to update.
   */
  where: Prisma.EmployeeRequestWhereUniqueInput
}

/**
 * EmployeeRequest updateMany
 */
export type EmployeeRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EmployeeRequests.
   */
  data: Prisma.XOR<Prisma.EmployeeRequestUpdateManyMutationInput, Prisma.EmployeeRequestUncheckedUpdateManyInput>
  /**
   * Filter which EmployeeRequests to update
   */
  where?: Prisma.EmployeeRequestWhereInput
  /**
   * Limit how many EmployeeRequests to update.
   */
  limit?: number
}

/**
 * EmployeeRequest updateManyAndReturn
 */
export type EmployeeRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * The data used to update EmployeeRequests.
   */
  data: Prisma.XOR<Prisma.EmployeeRequestUpdateManyMutationInput, Prisma.EmployeeRequestUncheckedUpdateManyInput>
  /**
   * Filter which EmployeeRequests to update
   */
  where?: Prisma.EmployeeRequestWhereInput
  /**
   * Limit how many EmployeeRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EmployeeRequest upsert
 */
export type EmployeeRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the EmployeeRequest to update in case it exists.
   */
  where: Prisma.EmployeeRequestWhereUniqueInput
  /**
   * In case the EmployeeRequest found by the `where` argument doesn't exist, create a new EmployeeRequest with this data.
   */
  create: Prisma.XOR<Prisma.EmployeeRequestCreateInput, Prisma.EmployeeRequestUncheckedCreateInput>
  /**
   * In case the EmployeeRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmployeeRequestUpdateInput, Prisma.EmployeeRequestUncheckedUpdateInput>
}

/**
 * EmployeeRequest delete
 */
export type EmployeeRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
  /**
   * Filter which EmployeeRequest to delete.
   */
  where: Prisma.EmployeeRequestWhereUniqueInput
}

/**
 * EmployeeRequest deleteMany
 */
export type EmployeeRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmployeeRequests to delete
   */
  where?: Prisma.EmployeeRequestWhereInput
  /**
   * Limit how many EmployeeRequests to delete.
   */
  limit?: number
}

/**
 * EmployeeRequest without action
 */
export type EmployeeRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeRequest
   */
  select?: Prisma.EmployeeRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmployeeRequest
   */
  omit?: Prisma.EmployeeRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeRequestInclude<ExtArgs> | null
}
